-- =============================================================================
-- FULL PRODUCTION SYNC MIGRATIONS (Run these if updating an existing database)
-- =============================================================================
-- Note: MariaDB supports 'IF NOT EXISTS' for ADD COLUMN. 
-- This block ensures every single column across all tables exists.

ALTER TABLE `admins` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS name VARCHAR(150) NOT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(150) NOT NULL UNIQUE,
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS role ENUM('super_admin', 'admin', 'moderator') DEFAULT 'admin',
    ADD COLUMN IF NOT EXISTS status BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS last_login DATETIME NULL,
    ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45) NULL,
    ADD COLUMN IF NOT EXISTS password_updated_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `users` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS profile_id VARCHAR(20) UNIQUE,
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS mobile VARCHAR(20) NOT NULL,
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(10),
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255),
    ADD COLUMN IF NOT EXISTS are_you_digambar_jain ENUM('Yes','No') DEFAULT 'Yes',
    ADD COLUMN IF NOT EXISTS gender ENUM('Male','Female'),
    ADD COLUMN IF NOT EXISTS birth_date DATE,
    ADD COLUMN IF NOT EXISTS birth_time TIME,
    ADD COLUMN IF NOT EXISTS birth_place VARCHAR(255),
    ADD COLUMN IF NOT EXISTS native_place VARCHAR(255),
    ADD COLUMN IF NOT EXISTS gotra VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mama_gotra VARCHAR(255),
    ADD COLUMN IF NOT EXISTS manglik ENUM('Yes','No'),
    ADD COLUMN IF NOT EXISTS height VARCHAR(20),
    ADD COLUMN IF NOT EXISTS weight DECIMAL(5,2),
    ADD COLUMN IF NOT EXISTS marital_status ENUM('Never Married', 'Widow', 'Widower', 'Divorce') DEFAULT 'Never Married',
    ADD COLUMN IF NOT EXISTS handicapped ENUM('Yes','No') DEFAULT 'No',
    ADD COLUMN IF NOT EXISTS higher_education TEXT,
    ADD COLUMN IF NOT EXISTS occupation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS company_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS designation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS monthly_income DECIMAL(12,2),
    ADD COLUMN IF NOT EXISTS languages TEXT,
    ADD COLUMN IF NOT EXISTS hobbies TEXT,
    ADD COLUMN IF NOT EXISTS partner_preference TEXT,
    ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(255),
    ADD COLUMN IF NOT EXISTS family_photo VARCHAR(255),
    ADD COLUMN IF NOT EXISTS profile_photo_drive_url TEXT,
    ADD COLUMN IF NOT EXISTS payment_screenshot VARCHAR(255),
    ADD COLUMN IF NOT EXISTS payment_proof_drive_url TEXT,
    ADD COLUMN IF NOT EXISTS permanent_address TEXT,
    ADD COLUMN IF NOT EXISTS pin_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS current_address TEXT,
    ADD COLUMN IF NOT EXISTS father_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS father_mobile VARCHAR(50),
    ADD COLUMN IF NOT EXISTS father_income VARCHAR(100),
    ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_mobile VARCHAR(50),
    ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_occupation_details VARCHAR(255),
    ADD COLUMN IF NOT EXISTS brothers INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS brothers_married INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS brothers_unmarried INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters_married INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters_unmarried INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS subcast VARCHAR(255),
    ADD COLUMN IF NOT EXISTS custom_subcast VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mandir VARCHAR(255),
    ADD COLUMN IF NOT EXISTS custom_mandir VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ref1_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ref1_mobile VARCHAR(50),
    ADD COLUMN IF NOT EXISTS ref1_relation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS ref2_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ref2_mobile VARCHAR(50),
    ADD COLUMN IF NOT EXISTS ref2_relation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS status ENUM('account_pending', 'account_approved', 'pending', 'approved', 'rejected', 'blocked') DEFAULT 'account_pending',
    ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS approved_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS approved_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS featured_until DATE NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS registration_source ENUM('website', 'google_form', 'admin') DEFAULT 'website',
    ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `user_addresses` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS permanent_address TEXT,
    ADD COLUMN IF NOT EXISTS permanent_pin_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS current_address TEXT,
    ADD COLUMN IF NOT EXISTS current_pin_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS city VARCHAR(100),
    ADD COLUMN IF NOT EXISTS state VARCHAR(100),
    ADD COLUMN IF NOT EXISTS country VARCHAR(100),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `family_details` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS father_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS father_mobile VARCHAR(20),
    ADD COLUMN IF NOT EXISTS father_income DECIMAL(12,2),
    ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_mobile VARCHAR(20),
    ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(255),
    ADD COLUMN IF NOT EXISTS brothers INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS brothers_married INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS brothers_unmarried INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters_married INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sisters_unmarried INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `memberships` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS plan_name VARCHAR(100) NOT NULL,
    ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) NOT NULL,
    ADD COLUMN IF NOT EXISTS duration_days INT NOT NULL,
    ADD COLUMN IF NOT EXISTS contact_limit INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS featured_profile BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS priority_support BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS status BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL;

ALTER TABLE `user_memberships` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS membership_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS start_date DATE,
    ADD COLUMN IF NOT EXISTS end_date DATE,
    ADD COLUMN IF NOT EXISTS status ENUM('active', 'expired', 'cancelled') DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS can_view_contacts BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `payments` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS membership_id BIGINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS amount DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(100),
    ADD COLUMN IF NOT EXISTS payment_remarks TEXT,
    ADD COLUMN IF NOT EXISTS payment_screenshot VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status ENUM('pending', 'verified', 'rejected') DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS verified_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `contact_messages` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS subject VARCHAR(255),
    ADD COLUMN IF NOT EXISTS message TEXT,
    ADD COLUMN IF NOT EXISTS status ENUM('unread', 'read', 'replied') DEFAULT 'unread',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `success_stories` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS couple_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS city VARCHAR(255),
    ADD COLUMN IF NOT EXISTS engagement_date DATE,
    ADD COLUMN IF NOT EXISTS marriage_date DATE,
    ADD COLUMN IF NOT EXISTS story LONGTEXT,
    ADD COLUMN IF NOT EXISTS photo VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status ENUM('pending', 'approved') DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `community_events` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS description LONGTEXT,
    ADD COLUMN IF NOT EXISTS event_date DATE,
    ADD COLUMN IF NOT EXISTS location VARCHAR(255),
    ADD COLUMN IF NOT EXISTS banner VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `advertisements` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS image VARCHAR(255),
    ADD COLUMN IF NOT EXISTS link VARCHAR(255),
    ADD COLUMN IF NOT EXISTS position ENUM('home_top', 'home_bottom', 'sidebar'),
    ADD COLUMN IF NOT EXISTS status BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `site_settings` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS site_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS site_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS site_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS site_address TEXT,
    ADD COLUMN IF NOT EXISTS upi_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS facebook VARCHAR(255),
    ADD COLUMN IF NOT EXISTS instagram VARCHAR(255),
    ADD COLUMN IF NOT EXISTS youtube VARCHAR(255),
    ADD COLUMN IF NOT EXISTS logo VARCHAR(255),
    ADD COLUMN IF NOT EXISTS favicon VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `activity_logs` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_type ENUM('admin', 'user'),
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS action VARCHAR(255),
    ADD COLUMN IF NOT EXISTS details TEXT,
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(100),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `import_history` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS imported_records INT,
    ADD COLUMN IF NOT EXISTS imported_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS import_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `members` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS gender ENUM('Male', 'Female', 'Other'),
    ADD COLUMN IF NOT EXISTS birth_date DATE,
    ADD COLUMN IF NOT EXISTS birth_time TIME,
    ADD COLUMN IF NOT EXISTS birth_place VARCHAR(255),
    ADD COLUMN IF NOT EXISTS native VARCHAR(100),
    ADD COLUMN IF NOT EXISTS gotra VARCHAR(100),
    ADD COLUMN IF NOT EXISTS mama_gotra VARCHAR(100),
    ADD COLUMN IF NOT EXISTS manglik ENUM('yes', 'no'),
    ADD COLUMN IF NOT EXISTS height_cm SMALLINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(5,2),
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(5),
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS permanent_address TEXT,
    ADD COLUMN IF NOT EXISTS permanent_pin_code CHAR(6),
    ADD COLUMN IF NOT EXISTS current_address TEXT,
    ADD COLUMN IF NOT EXISTS higher_education TEXT,
    ADD COLUMN IF NOT EXISTS occupation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS company_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS designation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS monthly_income DECIMAL(12,2),
    ADD COLUMN IF NOT EXISTS father_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS father_mobile VARCHAR(20),
    ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS father_monthly_income DECIMAL(12,2),
    ADD COLUMN IF NOT EXISTS mother_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mother_mobile VARCHAR(20),
    ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS brothers_total TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS brothers_married TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS brothers_unmarried TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS sisters_total TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS sisters_married TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS sisters_unmarried TINYINT UNSIGNED,
    ADD COLUMN IF NOT EXISTS partner_preferences TEXT,
    ADD COLUMN IF NOT EXISTS languages_known TEXT,
    ADD COLUMN IF NOT EXISTS hobbies TEXT,
    ADD COLUMN IF NOT EXISTS widow_divorce ENUM('widow', 'divorcee', 'none'),
    ADD COLUMN IF NOT EXISTS handicapped_physical_deficiency TEXT,
    ADD COLUMN IF NOT EXISTS profile_photo_path VARCHAR(500),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `import_images` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS image_type VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS member_name_key VARCHAR(255),
    ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS file_path VARCHAR(500) NOT NULL,
    ADD COLUMN IF NOT EXISTS file_size_bytes BIGINT;

ALTER TABLE `password_resets` 
    ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT,
    ADD COLUMN IF NOT EXISTS `email` varchar(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS `token` varchar(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS `created_at` datetime NOT NULL DEFAULT current_timestamp();

ALTER TABLE `account_requests` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS request_type ENUM('deactivation', 'deletion') DEFAULT 'deletion',
    ADD COLUMN IF NOT EXISTS reason TEXT,
    ADD COLUMN IF NOT EXISTS status ENUM('pending', 'processed', 'rejected') DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `registration_fields` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS field_group VARCHAR(100) DEFAULT 'Basic Details',
    ADD COLUMN IF NOT EXISTS field_key VARCHAR(100) NOT NULL UNIQUE,
    ADD COLUMN IF NOT EXISTS field_label VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS field_type VARCHAR(50) DEFAULT 'text',
    ADD COLUMN IF NOT EXISTS field_options TEXT,
    ADD COLUMN IF NOT EXISTS is_custom BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_required BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_core BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `user_custom_data` 
    ADD COLUMN IF NOT EXISTS id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS user_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS field_id BIGINT UNSIGNED NOT NULL,
    ADD COLUMN IF NOT EXISTS field_value TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

